### ISSUE TITLE
inventaires vehicules

### ISSUE THREAD

**Issue by FOBARMA3** [FOBARMA3/FOB-2sierra#27]
impossible de remettre un objet pris dans l'inventaire du vehicule

**Comment by prayerz** [comment]
Noxx, les véhicules sont "surchargés", dans toutes les missions de Whitzler c'est déjà le cas, de ce fait la place dispo est déjà pleine même si tu retires un objet.

A moins de réduire drastiquement l'équipement présent, on ne pourra corriger ce point

**Comment by FOBARMA3** [comment]
Ok  c est noté.
Merci Dream et bon WE, tu m enverras les photos haha!!

Envoyé de mon iPad
